### ISSUE TITLE
[Suggestion] Cookie.

### ISSUE THREAD

**Issue by ghost** [AutoUOC/site#29] opened 2020-08-27 16:20 UTC
In case you add cookies:
https://pastebin.com/Hig30Jd8

Just add that in the head section and you're ready to go lol

**Comment by ghost** [comment] 2020-08-27 16:20
Also you can use this to test it: https://mrdoob.com/projects/htmleditor/

**Comment by bremea** [comment] 2020-08-27 16:54
This is a duplicate of issue #18. Please make more constructive issues & pulls or you will be blocked from this repo.

**Closed as completed by bremea** 2020-08-27 16:54 UTC
Labels: enhancement

**Comment by ghost** [comment] 2020-08-27 17:02
> This is a duplicate of issue #18. Please make more constructive issues & pulls or you will be blocked from this repo.

No, it isn't! Here i am suggesting a cookie message, not to add cookies!
